### ISSUE TITLE
Doesn't use correct indentation when using "open file"

### ISSUE THREAD

**Issue by treyhunner** [danielgcf/editorconfig-eclipse#1]
I tried following the first indentation test [here](https://github.com/editorconfig/editorconfig-plugin-tests/blob/master/tests/indentation.rst) and the test failed.  I used "open file" to open the file.

The indentation inserted was tabs, not spaces.

**Comment by treyhunner** [comment]
Closing because I believe I didn't properly install the plugin.

**Comment by danielgcf** [comment]
I didn't know this test plan.. I actually just did the test using the current file.. I'll have a look and be guided by this test.

**Comment by treyhunner** [comment]
@danielgcf I couldn't figure out how to install the plugin from the git repo or zip file (since it's not an existing project).

Could you create instructions for an Eclipse beginner (like me) so I can try again later?  Thanks!

**Comment by danielgcf** [comment]
I'm sorry the read.me is terrible.. I'll get it better from tomorrow.. I'm not used with it yet.
I tried to explain better, hope you can do it.
You might need to install MAVEN. I submited so you guys could have a look.. i'll find a better way to deploy it.

**Comment by danielgcf** [comment]
@treyhunner Hi, just left a easier way so you can install the plugin.

Go the the release tab and there will be a .jar file. 

Put it on the eclipse/dropins folder.

**Comment by danielgcf** [comment]
@treyhunner  Based on the test i'm understanding .editorconfig way of work. Right know the plugin just works with [*] it doesn't work with specif files or format.. is like all in.. i'll try to handle that.
